#!/bin/bash

echo "NODE_ENV : $( echo -n "development" | base64 )"
echo "PORT : $( echo -n "9095" | base64 )"
echo "BOOTSTRAP : $( echo -n "1" | base64 )"
echo "APP_ID : $( echo -n "MCI-Gateway" | base64 )"
echo "LOG_LEVEL : $( echo -n "debug" | base64 )"
echo "REQUEST_LIMIT : $( echo -n "50kb" | base64 )"
echo "SESSION_SECRET : $( echo -n "mci-gateway" | base64 )"
echo "OPENAPI_SPEC : $( echo -n "/v1/spec" | base64 )"
echo "OPENAPI_ENABLE_RESPONSE_VALIDATION : $( echo -n "false" | base64 )"
echo "DB_HOST : $( echo -n "18.191.119.150" | base64 )"
echo "DB_NAME : $( echo -n "dev" | base64 )"
echo "DB_USERNAME : $( echo -n "technox-admin" | base64 )"
echo "DB_PASSWORD : $( echo -n "tEcHnOx#431" | base64 )"
echo "MATLS_SSO : $( echo -n "https://matls-sso.openbankingtest.org.uk" | base64 )"
echo "MATLS_API : $( echo -n "https://matls-api.openbankingtest.org.uk" | base64 )"
echo "MATLS_DIRAPI : $( echo -n "https://matls-dirapi.openbankingtest.org.uk" | base64 )"
echo "EMAIL_API_KEY : $( echo -n "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" | base64 )"
echo "EMAIL_DOMAIN : $( echo -n "sagar.khan@coditas.com" | base64 )"
echo "BASE_URL : $( echo -n "https://mci-dev.technoxander.com" | base64 )"
echo "TPP_CLIENT : $( echo -n "https://mci-dev.technoxander.com/public/tpp-client" | base64 )"
echo "PROXY_URL : $( echo -n "http://www.technoxander.com" | base64 )"