apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mci-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: 	subnet-1608e66b, 	subnet-62853509
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:583831198490:certificate/1c8417e3-17e1-4c92-b648-10d60dce4ac3
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
  labels:
    app: mci-frontend
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: mci-frontend
              servicePort: 3080

            

# apiVersion: extensions/v1beta1 
# kind: Ingress 
# metadata: 
#   namespace: default 
#   name: ingress 
#   annotations: 
#     kubernetes.io/ingress.class: alb 
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]' 
# spec: 
#   tls: 
#     - hosts: www.example.com 
#       rules: 
#       - http: 
#         paths: 
#           - path: /users/* 
#             backend: 
#                 serviceName: user-service 
#                 servicePort: 80