apiVersion: v1
kind: Service
metadata:
  name: mci-frontend-lb
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:583831198490:certificate/b689fe0d-12b9-4657-9785-2aae85c3c8f9
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: mci-frontend
  ports:
  - name: http
    port: 80
    targetPort: 3080
  - name: https
    port: 443
    targetPort: 3080
  type: LoadBalancer